### ISSUE TITLE
Pen doesn't work on windows ink mode

### ISSUE THREAD

**Issue by PuzThePuzzle** [X9VoiD/VoiDPlugins#13]
The pen doesn't move or respond at all when on windows ink absolute or relative mode, the standard ones work just fine

**Comment by X9VoiD** [comment]
Did you read and follow the instructions from [wiki](https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk)?

**Comment by PuzThePuzzle** [comment]
Yes, using windows ink absolute mode and windows ink pen tip stops
detecting the pen.

**Comment by X9VoiD** [comment]
Did you install [VMulti](https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk#requirements)?

**Comment by PuzThePuzzle** [comment]
Yes, I think so.
I tried to uninstall and install just to make sure, but now the .bat closes
without warning a couple of seconds after giving it admin permissions

**Comment by radfah** [comment]
I have the exact same issue. The cmd closes immediately after running .cmd file, how did you "mess around" with it to fix that problem?
