### ISSUE TITLE
Plugin/Script Runner Request

### ISSUE THREAD

**Issue by The-Mach34** [X9VoiD/VoiDPlugins#14]
Could you maybe add the ability to add shortcuts like *ctrl + z* to the Script Runner plugin or maybe write a similar plugin to do something like that? That would be pretty helpful and I think pretty easy to add. Thanks.

**Comment by X9VoiD** [comment]
Resolved by OpenTabletDriver's [#1015](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/1015).
