### ISSUE TITLE
Eraser button in Onenote

### ISSUE THREAD

**Issue by kris657** [X9VoiD/VoiDPlugins#15]
Windows Ink: Eraser (Hold) and Windows Ink: Eraser (toggle) buttons dont seem to work within Onenote for windows 10. The eraser button functionallity works when using the base Wacom drivers but not when using OpenTabletDriver with WindowsInk plugin

**Comment by X9VoiD** [comment]
Did you install [VMulti](https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk#requirements) and followed [Setup](https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk#setup)?

**Comment by kris657** [comment]
> Did you install [VMulti](https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk#requirements) and followed [Setup](https://github.com/X9VoiD/VoiDPlugins/wiki/WindowsInk#setup)?

Yes, i followed the setup and installed Vmulti. The pen and the features works besides the eraser button functionality. The Eraser button seems to do something, as the UI flickers off the pen mode but  it does not activate the eraser button functionality

**Comment by maroru** [comment]
If you were using any drivers such as hawku drivers or Wacom drivers before did you properly uninstall them? What tablet and pen are you using? I'm using the Wacom One CTL-472 and the eraser works for me on OneNote.

Keep in mind that the VMulti you need to download and install is not the VMultiMode OTD plugin but actually its own driver [(linked here).](https://github.com/X9VoiD/vmulti-bin/releases/tag/v1.0)


You could try a fresh reinstall by deleting all drivers and plugins and uninstalling and reinstalling OpenTabletDriver, VMulti, and the Windows Ink plugin and see if it works.

**Comment by X9VoiD** [comment]
Fixed in this [commit](d36f363461db7944af53c3dfe7ad6f76c6d56779).
