### ISSUE TITLE
windows ink disconects my g640 after touching the tablet

### ISSUE THREAD

**Issue by Schnitzelflo44** [X9VoiD/VoiDPlugins#24]
https://user-images.githubusercontent.com/68322498/146260829-2383ae3e-a527-48f2-acb9-6673ff909262.mp4

its disconecting after pressing on the tablet

My only on OpenTabletDriver plugins are:

VMultiMode
Windows Ink

I have a XP-Pen Star G640

**Comment by X9VoiD** [comment]
Make sure that you have installed [VMulti](https://github.com/X9VoiD/vmulti-bin/releases/tag/v1.0).
