### ISSUE TITLE
Reconstructor is incompatible with OTD v0.6.0.0

### ISSUE THREAD

**Issue by Zyfarok** [X9VoiD/VoiDPlugins#25]
```
[Plugin:Warning]	Plugin 'Reconstructor, Version=1.0.0.0' can't be loaded and is likely out of date. (HResult: 0x80131602)
Unable to load one or more of the requested types.
Could not load type 'OpenTabletDriver.Plugin.Tablet.IFilter' from assembly 'OpenTabletDriver.Plugin, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at OpenTabletDriver.Desktop.Reflection.PluginManager.IsLoadable(Assembly asm)
```

**Comment by Kuuuube** [comment]
Use the latest actions build. Reconstructor is up to date but has not been released yet.

https://github.com/X9VoiD/VoiDPlugins/actions

**Comment by Zyfarok** [comment]
I uninstalled the plugin, downloaded the reconstructor.zip file from the latest actions build here :
https://github.com/X9VoiD/VoiDPlugins/actions/runs/1688996928

Then imported this newly plugin by drag and droping the zip and it produces the exact same log again.

**Comment by Zyfarok** [comment]
Ok, I tried deleting the whole OTD folder and reinstalling it properly and it seems to work now.

There might have been something going wrong with OTD when uninstalling or installing the plugin.
