### ISSUE TITLE
Tablet reports without position data set cursor back to last location in windows ink and vmultimode

### ISSUE THREAD

**Issue by Kuuuube** [X9VoiD/VoiDPlugins#27]
Tablet reports without position data pull the cursor back to the location of the last position report. Happens even when the pen is not on the tablet as long as any report is sent.

Tested on 3dd078ea2d344b3a9821b165ed82b655384d1633 and OTD v0.6.0.1

Example reports from Wacom PTH-460:
Idle reports: [tablet-data.txt](https://github.com/X9VoiD/VoiDPlugins/files/7858870/tablet-data.txt)
Touch reports: [tablet-data.txt](https://github.com/X9VoiD/VoiDPlugins/files/7858871/tablet-data.txt)
Pressing buttons: [tablet-data.txt](https://github.com/X9VoiD/VoiDPlugins/files/7858873/tablet-data.txt)

**Comment by myangelaku** [comment]
[Video of the bug in question](https://www.youtube.com/watch?v=6J27M_cGxsc)

**Comment by UxieBl** [comment]
this happens on my desktop pc but not my laptop, however I can't seem to figure out why that is

maybe it has to do with windows versions?

**Comment by myangelaku** [comment]
> this happens on my desktop pc but not my laptop, however I can't seem to figure out why that is
> 
> maybe it has to do with windows versions?

Huh, that's weird. I'm on Windows 10.0.19044 Home

**Comment by UxieBl** [comment]
my desktop is on 10.0.19043 and my laptop is on 19042

the laptop doesn't have pen shortcuts in the windows ink settings, so maybe they changed some stuff about how ink functions

I noticed in your video that yours happens a lot more frequently as your report rate is up to 7hz in the debug, but mine is a lot slower at a rate of 1hz or less (I have a ctl-480)

not sure if any of that helps, but it might be worth noting

**Comment by KuShirosu** [comment]
my cursor is go back every 5 seconds. i'm using wacom tablet CTH-680, windows 11

**Comment by Kuuuube** [comment]
Appears to be fixed with v0.3.2
