### ISSUE TITLE
TouchEmu crashes (every version of the plugin, every version of OTD, that I have tried)

### ISSUE THREAD

**Issue by Doksha** [X9VoiD/VoiDPlugins#30]
I had gotten Touch Emu to work once, but it was extremely spotty and crashed a lot, no matter what version of OTD it would crash after a few minutes if I was lucky (normally it crashes instantly) I have spent so much time trying to get this plugin to work as it is exactly what I need, but no matter what I do it will crash. I have tried on multiple computers so it isnt a computer specific thing. When it works, it actually works and I can use it as a touch device, but most of the time it just crashes.
(using windows 10, so windows version shouldnt be an issue)

**Comment by Doksha** [comment]
Please find a way to fix this, its been an issue for so long and its one of the only actually useful plugins for OTD. Sadly for since I have a newer version of OTD installed, I cant download older versions as they instantly break, so I have no way of reverting to a working version of the plugin.

**Comment by jamesbt365** [comment]
Remove the new settings file if you want to use the old versions of opentabletdriver

**Comment by THEec2** [comment]
Crashes alot for me. Crashes when I click apply with the pen on the tablet. Also, please add a way to change the touchemu cursor. I can't see the current one when I move the pen too fast.

**Comment by jamesbt365** [comment]
Windows changed the api for that stuff so it does not work on never versions of windows at the moment, and they didn't document anything either so its hard to fix fyi

**Comment by Polyterative** [comment]
Crashing for me as well :/

**Comment by X9VoiD** [comment]
Can't reproduce.
