### ISSUE TITLE
[VMultiMode] Width incorrect on screen output

### ISSUE THREAD

**Issue by C0D3-M4513R** [X9VoiD/VoiDPlugins#36]
To make VMulti Absolute output work for me, I had to set my display output to span both my main and secondary monitor. If I don't, my cursor will be stuck on the right 2/3 of my main screen. (I have a 2560x1440 main and 1920x1080 to the left of my main) (Normal Absolute mode has absolutely no issues for me)
Also if I set the output display to cover only my secondary monitor, the cursor is still on my primary monitor, but restrained to a area similar of my secondary monitor.

**Comment by jamesbt365** [comment]
This is a vmulti bug itself.

**Comment by jamesbt365** [comment]
Vmulti driver has gone a decade without updating. Its not surprising it is dying as stuff changes

**Comment by X9VoiD** [comment]
Will close as an external issue. All drivers, including OEMs that utilize VMulti suffer from the same bug.
