### ISSUE TITLE
Vmulti driver doesnt work in 10moon 1060N

### ISSUE THREAD

**Issue by Draxler101** [X9VoiD/VoiDPlugins#40]
Hi there Vmulti relative mode is not work can move cursor or click and vmulti absolute mode can move cursor but cant click anywhere

**Comment by Draxler101** [comment]
I have windows 11 
ryzen 5800x 
amd radeon6600

**Comment by jamesbt365** [comment]
Make sure that your reset time is not set to 0. It is also important that you have vmulti driver installed (not the same as the plugin). And as for click not working you need to use the vmulti left click binding. You should read the wiki if you need further guideance.

**Comment by jamesbt365** [comment]
Actually the clicking issue can also be an issue with OTD as the parser is a little messed up, so if it doesn't work properly its a known issue and worked on upstream.

**Comment by X9VoiD** [comment]
Closing since this is user error.
