### ISSUE TITLE
Windows Ink mode locking cursor on the right screen edge

### ISSUE THREAD

**Issue by OmegaRogue** [X9VoiD/VoiDPlugins#7]
when i enable windows ink mode, the cursor gets locked to the right edge of the screen, even though the tablet area and screen area are set to cover the whole screen

**Comment by OmegaRogue** [comment]
also windows ink seems to not have any ink specific binding options, so stuff like an eraser key or the shortcut key aren't available, the only thing it seems to currently do is basic pen tip support

**Comment by OmegaRogue** [comment]
and Artist Mode (Relative Windows Ink) doesn't appear in the list of output modes

**Comment by OmegaRogue** [comment]
im trying to see if I can fix it myself but projects in the OpenTabletDriver Solution being referenced in the .modules directory is causing problems with loading the solution, JetBrains Rider can't seem to find the Projects

**Comment by OmegaRogue** [comment]
i built it myself and now it crashes everytime I enable it

**Comment by X9VoiD** [comment]
WindowsInk uses the basic left, right, and middle to bind pen touch, eraser, and barrel buttons respectively.

If you are using multi-monitor then those issues are going to be fixed on next OTD release (or build OTD master branch)

All plugins on `master` branch is compatible only on `master` branch of OTD, and also requires you to initialize the git submodule if building from source.

```git submodule update --init --remote```

If I have answered all your questions then you may close the issue.
